ALTER TYPE "VehiclePhotoType" ADD VALUE IF NOT EXISTS 'LOGBOOK';
ALTER TYPE "VehiclePhotoType" ADD VALUE IF NOT EXISTS 'NTSA_INSPECTION';
ALTER TYPE "VehiclePhotoType" ADD VALUE IF NOT EXISTS 'GOODS_TRANSPORT_LICENSE';
ALTER TYPE "VehiclePhotoType" ADD VALUE IF NOT EXISTS 'ROAD_SERVICE_LICENSE';
ALTER TYPE "VehiclePhotoType" ADD VALUE IF NOT EXISTS 'AXLE_LOAD_CERTIFICATE';
