const { AccountStatus, UserRole } = require('@prisma/client');

const AGENCIES = [
  {
    name: 'Zito Head Office',
    status: 'ACTIVE',
    address: 'Nairobi Head Office',
  },
  {
    name: 'QA Internal Agency',
    status: 'ACTIVE',
    address: 'Nairobi, Kenya',
  },
  {
    name: 'QA Coast Agency',
    status: 'ACTIVE',
    address: 'Mombasa, Kenya',
  },
];

const USERS = [
  {
    fullName: 'Demo Individual Customer',
    email: 'customer.demo@zito.local',
    phone: '+919870000101',
    password: 'Customer@123',
    role: UserRole.CUSTOMER,
    status: AccountStatus.ACTIVE,
    notes: 'Primary customer demo account',
  },
  {
    fullName: 'QA Customer',
    email: 'qa.customer@zito.local',
    phone: '+254711000101',
    password: 'QaCustomer@123',
    role: UserRole.CUSTOMER,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Corporate',
    companyName: 'QA Corporate Logistics',
    email: 'qa.corporate@zito.local',
    phone: '+254711000102',
    password: 'QaCorporate@123',
    role: UserRole.CORPORATE,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Driver',
    email: 'qa.driver@zito.local',
    phone: '+254711000104',
    password: 'QaDriver@123',
    role: UserRole.DRIVER,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Agent',
    companyName: 'QA Agent Supply Desk',
    email: 'qa.agent@zito.local',
    phone: '+254711000114',
    password: 'QaAgent@123',
    role: UserRole.AGENT,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Transporter',
    companyName: 'QA Transporter Fleet',
    email: 'qa.transporter@zito.local',
    phone: '+254711000105',
    password: 'QaTransporter@123',
    role: UserRole.TRANSPORTER,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Courier',
    companyName: 'QA Courier Company',
    email: 'qa.courier@zito.local',
    phone: '+254711000103',
    password: 'QaCourier@123',
    role: UserRole.COURIER_COMPANY,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Warehouse',
    companyName: 'QA Warehouse Partner',
    email: 'qa.warehouse@zito.local',
    phone: '+254711000107',
    password: 'QaWarehouse@123',
    role: UserRole.WAREHOUSE_PARTNER,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Super Admin',
    email: 'qa.superadmin@zito.local',
    phone: '+254711000001',
    password: 'QaSuperAdmin@123',
    role: UserRole.SUPER_ADMIN,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'QA Admin',
    email: 'qa.admin@zito.local',
    phone: '+254711000002',
    password: 'QaAdmin@123',
    role: UserRole.ADMIN,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'Vishal Golatkar',
    email: 'vishalgolatkar@yahoo.com',
    phone: '+254745759921',
    password: 'VishalAdmin@2026',
    role: UserRole.ADMIN,
    status: AccountStatus.ACTIVE,
    notes: 'Primary admin used for local sign-in verification',
  },
  {
    fullName: 'Head Office Operations',
    email: 'head.ops@zito.local',
    phone: '+254711000108',
    password: 'HeadOps@123',
    role: UserRole.AGENCY_STAFF,
    status: AccountStatus.ACTIVE,
    staffRole: 'OPERATIONS',
    staffScope: 'HEAD_OFFICE',
    agencyName: 'Zito Head Office',
  },
  {
    fullName: 'Head Office Customer Care',
    email: 'head.care@zito.local',
    phone: '+254711000109',
    password: 'HeadCare@123',
    role: UserRole.AGENCY_STAFF,
    status: AccountStatus.ACTIVE,
    staffRole: 'CUSTOMER_CARE',
    staffScope: 'HEAD_OFFICE',
    agencyName: 'Zito Head Office',
  },
  {
    fullName: 'Head Office Accounts',
    email: 'head.accounts@zito.local',
    phone: '+254711000110',
    password: 'HeadAccounts@123',
    role: UserRole.AGENCY_STAFF,
    status: AccountStatus.ACTIVE,
    staffRole: 'ACCOUNTS',
    staffScope: 'HEAD_OFFICE',
    agencyName: 'Zito Head Office',
  },
  {
    fullName: 'Agency Operations Desk',
    email: 'agency.ops@zito.local',
    phone: '+254711000111',
    password: 'AgencyOps@123',
    role: UserRole.AGENCY_STAFF,
    status: AccountStatus.ACTIVE,
    staffRole: 'OPERATIONS',
    staffScope: 'AGENCY',
    agencyName: 'QA Internal Agency',
  },
  {
    fullName: 'Agency Customer Care Desk',
    email: 'agency.care@zito.local',
    phone: '+254711000112',
    password: 'AgencyCare@123',
    role: UserRole.AGENCY_STAFF,
    status: AccountStatus.ACTIVE,
    staffRole: 'CUSTOMER_CARE',
    staffScope: 'AGENCY',
    agencyName: 'QA Internal Agency',
  },
  {
    fullName: 'Agency Accounts Desk',
    email: 'agency.accounts@zito.local',
    phone: '+254711000113',
    password: 'AgencyAccounts@123',
    role: UserRole.AGENCY_STAFF,
    status: AccountStatus.ACTIVE,
    staffRole: 'ACCOUNTS',
    staffScope: 'AGENCY',
    agencyName: 'QA Coast Agency',
  },
  {
    fullName: 'Smoke Admin',
    email: 'smoke.admin@example.com',
    phone: '+254700000001',
    password: 'SmokeAdmin@123',
    role: UserRole.ADMIN,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'Smoke Customer',
    email: 'smoke.customer.20260429183259@example.com',
    phone: '+254713488616',
    password: 'SmokeCustomer@123',
    role: UserRole.CUSTOMER,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'Devyanshu Negi',
    email: 'devyanshunegi@gmail.com',
    phone: '+918899209614',
    password: 'Devyanshu@123',
    role: UserRole.CUSTOMER,
    status: AccountStatus.ACTIVE,
  },
  {
    fullName: 'Vishal Golatkar',
    email: 'vishal31121987@gmail.com',
    phone: '+919768353573',
    password: 'VishalCustomer@123',
    role: UserRole.CUSTOMER,
    status: AccountStatus.ACTIVE,
  },
];

module.exports = {
  AGENCIES,
  USERS,
  HEAD_OFFICE_AGENCY_NAME: 'Zito Head Office',
};
